
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 22/10/2014 - 7:48
// This is a partial class file. The other one is TASK_ATTACHMENTEntity.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using System;
using Cooperator.Framework.Core.Exceptions;

namespace SISMONRules.Entities
{
    /// <summary>
    /// This class represents the TASK_ATTACHMENT entity.
    /// </summary>
    [Serializable]
    public partial class TASK_ATTACHMENT
    // : IValidable
    {
        // /// <summary>
        // /// When IValidable is implemented, this method is invoked by Gateway before Insert or Update to validate Object.
        // /// </summary>
        // public void Validate()
        // {
        //     //Example:
        //     if (string.IsNullOrEmpty(this.Name)) throw new RuleValidationException("Name can't be null");
        // }
        public string USERString { get; set; }
        public string Document_Title { get; set; }
        public string Required { get; set; }
    }

    /// <summary>
    /// This class represents a collection of TASK_ATTACHMENT entity.
    /// </summary>
    public partial class TASK_ATTACHMENTList
    {
        // /// <summary>
        // /// Returns a typed Dataset based on its content.
        // /// </summary>
        //public override System.Data.DataSet ToDataSet()
        //{
        //    YOUR_TYPED_DATASET MyDataSet = new YOUR_TYPED_DATASET();
        //    ObjectListHelper<TASK_ATTACHMENT, TASK_ATTACHMENTList> Exporter = new ObjectListHelper<TASK_ATTACHMENT, TASK_ATTACHMENTList>();
        //    Exporter.FillDataSet(MyDataSet, this);
        //    return MyDataSet;
        //}
    }
}

namespace SISMONRules.Views
{
    /// <summary>
    /// This class represents a view of an collection of TASK_ATTACHMENT entities.
    /// </summary>
    public partial class TASK_ATTACHMENTListView
    {
    }
}


