
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is PERMISSIONGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using SISMONRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace SISMONRules.Gateways
{

    public partial class PERMISSIONGateway : BaseGateway<PERMISSIONObject, PERMISSIONObjectList>, IGenericGateway
    {

        #region "Singleton"

        static PERMISSIONGateway _instance;

        private PERMISSIONGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static PERMISSIONGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new PERMISSIONGateway();
                else {
                    PERMISSIONGateway inst = HttpContext.Current.Items["SISMONRules.PERMISSIONGatewaySingleton"] as PERMISSIONGateway;
                    if (inst == null) {
                        inst = new PERMISSIONGateway();
                        HttpContext.Current.Items.Add("SISMONRules.PERMISSIONGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "PERMISSION"; }
        }

        protected override string RuleName
        {
            get {return typeof(PERMISSIONGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, PERMISSIONObject entity)
        {
            
            IMappeablePERMISSIONObject PERMISSION = (IMappeablePERMISSIONObject)entity;
            PERMISSION.HydrateFields(
            reader.GetInt32(0),
reader.GetInt32(1),
(reader.IsDBNull(2)) ? "" : reader.GetString(2),
(reader.IsDBNull(3)) ? "" : reader.GetString(3));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(PERMISSIONObject entity)
        {

            IMappeablePERMISSIONObject PERMISSION = (IMappeablePERMISSIONObject)entity;
            return PERMISSION.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(PERMISSIONObject entity)
        {

            IMappeablePERMISSIONObject PERMISSION = (IMappeablePERMISSIONObject)entity;
            return PERMISSION.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(PERMISSIONObject entity)
        {

            IMappeablePERMISSIONObject PERMISSION = (IMappeablePERMISSIONObject)entity;
            return PERMISSION.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(PERMISSIONObject row, object[] parameters)
        {
            ((IMappeablePERMISSIONObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "sm_";
        }


        /// <summary>
        /// Get a PERMISSIONObject by execute a SQL Query Text
        /// </summary>
        public PERMISSIONObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a PERMISSIONObjectList by execute a SQL Query Text
        /// </summary>
        public PERMISSIONObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a PERMISSIONObject by calling a Stored Procedure
        /// </summary>
        public PERMISSIONObject GetOne(System.Int32 Id_Project, System.Int32 Id_User)
        {
            return base.GetOne(new PERMISSIONObject(Id_Project, Id_User));
        }


        // GetBy Objects and Params
                                    
        /// <summary>
        /// Get a PERMISSIONObject by calling a Stored Procedure
        /// </summary>
        public PERMISSIONObject GetOne(IUniqueIdentifiable PROJECT, System.Int32 Id_User)
        {
        return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "PERMISSION_GetOne",  UniqueIdentifierHelper.ComposeIdentifier(PROJECT, Id_User));
        }   
                        


        

        /// <summary>
        /// Get a PERMISSIONObjectList by calling a Stored Procedure
        /// </summary>
        public PERMISSIONObjectList GetByPROJECT(DbTransaction transaction,System.Int32 Id_Project)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "PERMISSION_GetByPROJECT", Id_Project);
        }

        /// <summary>
        /// Get a PERMISSIONObjectList by calling a Stored Procedure
        /// </summary>
        public PERMISSIONObjectList GetByPROJECT(DbTransaction transaction, IUniqueIdentifiable PROJECT)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "PERMISSION_GetByPROJECT", PROJECT.Identifier());
        }

    

        /// <summary>
        /// Get a PERMISSIONObjectList by calling a Stored Procedure
        /// </summary>
        public PERMISSIONObjectList GetByUSER(DbTransaction transaction,System.Int32 Id_User)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "PERMISSION_GetByUSER", Id_User);
        }

        /// <summary>
        /// Get a PERMISSIONObjectList by calling a Stored Procedure
        /// </summary>
        public PERMISSIONObjectList GetByUSER(DbTransaction transaction, IUniqueIdentifiable USER)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "PERMISSION_GetByUSER", USER.Identifier());
        }

    

        

        /// <summary>
        /// Get a PERMISSIONObjectList by calling a Stored Procedure
        /// </summary>
        public PERMISSIONObjectList GetByPROJECT(System.Int32 Id_Project)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "PERMISSION_GetByPROJECT", Id_Project);
        }

        /// <summary>
        /// Get a PERMISSIONObjectList by calling a Stored Procedure
        /// </summary>
        public PERMISSIONObjectList GetByPROJECT(IUniqueIdentifiable PROJECT)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "PERMISSION_GetByPROJECT", PROJECT.Identifier());
        }

    

        /// <summary>
        /// Get a PERMISSIONObjectList by calling a Stored Procedure
        /// </summary>
        public PERMISSIONObjectList GetByUSER(System.Int32 Id_User)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "PERMISSION_GetByUSER", Id_User);
        }

        /// <summary>
        /// Get a PERMISSIONObjectList by calling a Stored Procedure
        /// </summary>
        public PERMISSIONObjectList GetByUSER(IUniqueIdentifiable USER)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "PERMISSION_GetByUSER", USER.Identifier());
        }

    

        /// <summary>
        /// Delete PERMISSION
        /// </summary>
        public void Delete(System.Int32 Id_Project, System.Int32 Id_User)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "PERMISSION_Delete", Id_Project, Id_User);
        }

        /// <summary>
        /// Delete PERMISSION
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 Id_Project, System.Int32 Id_User)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "PERMISSION_Delete", Id_Project, Id_User);
        }

                                    
        /// <summary>
        /// Delete PERMISSION
        /// </summary>
        public void Delete(IUniqueIdentifiable PROJECT, System.Int32 Id_User)
        {
        base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "PERMISSION_Delete",  UniqueIdentifierHelper.ComposeIdentifier(PROJECT, Id_User));
        }   
        /// <summary>
        /// Delete PERMISSION
        /// </summary>
        public void Delete(DbTransaction transaction, IUniqueIdentifiable PROJECT, System.Int32 Id_User)
        {
        base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "PERMISSION_Delete",  UniqueIdentifierHelper.ComposeIdentifier(PROJECT, Id_User));
        }   
                        

        

        /// <summary>
        /// Delete PERMISSION by PROJECT
        /// </summary>
        public void DeleteByPROJECT(System.Int32 Id_Project)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "PERMISSION_DeleteByPROJECT", Id_Project);
        }

        /// <summary>
        /// Delete PERMISSION by PROJECT
        /// </summary>
        public void DeleteByPROJECT(DbTransaction transaction, System.Int32 Id_Project)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "PERMISSION_DeleteByPROJECT", Id_Project);
        }

        /// <summary>
        /// Delete PERMISSION by PROJECT
        /// </summary>
        public void DeleteByPROJECT(IUniqueIdentifiable PROJECT)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "PERMISSION_DeleteByPROJECT", PROJECT.Identifier());
        }

        /// <summary>
        /// Delete PERMISSION by PROJECT
        /// </summary>
        public void DeleteByPROJECT(DbTransaction transaction, IUniqueIdentifiable PROJECT)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "PERMISSION_DeleteByPROJECT", PROJECT.Identifier());
        }


    

        /// <summary>
        /// Delete PERMISSION by USER
        /// </summary>
        public void DeleteByUSER(System.Int32 Id_User)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "PERMISSION_DeleteByUSER", Id_User);
        }

        /// <summary>
        /// Delete PERMISSION by USER
        /// </summary>
        public void DeleteByUSER(DbTransaction transaction, System.Int32 Id_User)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "PERMISSION_DeleteByUSER", Id_User);
        }

        /// <summary>
        /// Delete PERMISSION by USER
        /// </summary>
        public void DeleteByUSER(IUniqueIdentifiable USER)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "PERMISSION_DeleteByUSER", USER.Identifier());
        }

        /// <summary>
        /// Delete PERMISSION by USER
        /// </summary>
        public void DeleteByUSER(DbTransaction transaction, IUniqueIdentifiable USER)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "PERMISSION_DeleteByUSER", USER.Identifier());
        }


    


        //Database Queries 
        
            

        /// <summary>
        /// 
        /// </summary>
        public System.Int32 DeleteByProject(System.Int32 Id_Project) {
            
            return (System.Int32) base.DataBaseHelper.ExecuteScalarByStoredProcedure(StoredProceduresPrefix() + "PERMISSION_DeleteByProject" , Id_Project);
            
        }

        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 DeleteByProject(DbTransaction transaction , System.Int32 Id_Project) {
            
            return (System.Int32) base.DataBaseHelper.ExecuteScalarByStoredProcedure(transaction, StoredProceduresPrefix() + "PERMISSION_DeleteByProject" , Id_Project);
            
        }


        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








