
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is TASK_HISTORYGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using SISMONRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace SISMONRules.Gateways
{

    public partial class TASK_HISTORYGateway : BaseGateway<TASK_HISTORYObject, TASK_HISTORYObjectList>, IGenericGateway
    {

        #region "Singleton"

        static TASK_HISTORYGateway _instance;

        private TASK_HISTORYGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static TASK_HISTORYGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new TASK_HISTORYGateway();
                else {
                    TASK_HISTORYGateway inst = HttpContext.Current.Items["SISMONRules.TASK_HISTORYGatewaySingleton"] as TASK_HISTORYGateway;
                    if (inst == null) {
                        inst = new TASK_HISTORYGateway();
                        HttpContext.Current.Items.Add("SISMONRules.TASK_HISTORYGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "TASK_HISTORY"; }
        }

        protected override string RuleName
        {
            get {return typeof(TASK_HISTORYGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, TASK_HISTORYObject entity)
        {
            
            IMappeableTASK_HISTORYObject TASK_HISTORY = (IMappeableTASK_HISTORYObject)entity;
            TASK_HISTORY.HydrateFields(
            reader.GetInt32(0),
reader.GetInt32(1),
reader.GetString(2),
reader.GetDateTime(3));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(TASK_HISTORYObject entity)
        {

            IMappeableTASK_HISTORYObject TASK_HISTORY = (IMappeableTASK_HISTORYObject)entity;
            return TASK_HISTORY.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(TASK_HISTORYObject entity)
        {

            IMappeableTASK_HISTORYObject TASK_HISTORY = (IMappeableTASK_HISTORYObject)entity;
            return TASK_HISTORY.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(TASK_HISTORYObject entity)
        {

            IMappeableTASK_HISTORYObject TASK_HISTORY = (IMappeableTASK_HISTORYObject)entity;
            return TASK_HISTORY.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(TASK_HISTORYObject row, object[] parameters)
        {
            ((IMappeableTASK_HISTORYObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "sm_";
        }


        /// <summary>
        /// Get a TASK_HISTORYObject by execute a SQL Query Text
        /// </summary>
        public TASK_HISTORYObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a TASK_HISTORYObjectList by execute a SQL Query Text
        /// </summary>
        public TASK_HISTORYObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a TASK_HISTORYObject by calling a Stored Procedure
        /// </summary>
        public TASK_HISTORYObject GetOne(System.Int32 Id_Task_History)
        {
            return base.GetOne(new TASK_HISTORYObject(Id_Task_History));
        }


        // GetBy Objects and Params
            


        

        /// <summary>
        /// Get a TASK_HISTORYObjectList by calling a Stored Procedure
        /// </summary>
        public TASK_HISTORYObjectList GetByTASK(DbTransaction transaction,System.Int32 Id_Task)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "TASK_HISTORY_GetByTASK", Id_Task);
        }

        /// <summary>
        /// Get a TASK_HISTORYObjectList by calling a Stored Procedure
        /// </summary>
        public TASK_HISTORYObjectList GetByTASK(DbTransaction transaction, IUniqueIdentifiable TASK)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "TASK_HISTORY_GetByTASK", TASK.Identifier());
        }

    

        

        /// <summary>
        /// Get a TASK_HISTORYObjectList by calling a Stored Procedure
        /// </summary>
        public TASK_HISTORYObjectList GetByTASK(System.Int32 Id_Task)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "TASK_HISTORY_GetByTASK", Id_Task);
        }

        /// <summary>
        /// Get a TASK_HISTORYObjectList by calling a Stored Procedure
        /// </summary>
        public TASK_HISTORYObjectList GetByTASK(IUniqueIdentifiable TASK)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "TASK_HISTORY_GetByTASK", TASK.Identifier());
        }

    

        /// <summary>
        /// Delete TASK_HISTORY
        /// </summary>
        public void Delete(System.Int32 Id_Task_History)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "TASK_HISTORY_Delete", Id_Task_History);
        }

        /// <summary>
        /// Delete TASK_HISTORY
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 Id_Task_History)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "TASK_HISTORY_Delete", Id_Task_History);
        }

            

        

        /// <summary>
        /// Delete TASK_HISTORY by TASK
        /// </summary>
        public void DeleteByTASK(System.Int32 Id_Task)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "TASK_HISTORY_DeleteByTASK", Id_Task);
        }

        /// <summary>
        /// Delete TASK_HISTORY by TASK
        /// </summary>
        public void DeleteByTASK(DbTransaction transaction, System.Int32 Id_Task)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "TASK_HISTORY_DeleteByTASK", Id_Task);
        }

        /// <summary>
        /// Delete TASK_HISTORY by TASK
        /// </summary>
        public void DeleteByTASK(IUniqueIdentifiable TASK)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "TASK_HISTORY_DeleteByTASK", TASK.Identifier());
        }

        /// <summary>
        /// Delete TASK_HISTORY by TASK
        /// </summary>
        public void DeleteByTASK(DbTransaction transaction, IUniqueIdentifiable TASK)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "TASK_HISTORY_DeleteByTASK", TASK.Identifier());
        }


    


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








