
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is TASK_CONFIGURATIONGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using SISMONRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace SISMONRules.Gateways
{

    public partial class TASK_CONFIGURATIONGateway : BaseGateway<TASK_CONFIGURATIONObject, TASK_CONFIGURATIONObjectList>, IGenericGateway
    {

        #region "Singleton"

        static TASK_CONFIGURATIONGateway _instance;

        private TASK_CONFIGURATIONGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static TASK_CONFIGURATIONGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new TASK_CONFIGURATIONGateway();
                else {
                    TASK_CONFIGURATIONGateway inst = HttpContext.Current.Items["SISMONRules.TASK_CONFIGURATIONGatewaySingleton"] as TASK_CONFIGURATIONGateway;
                    if (inst == null) {
                        inst = new TASK_CONFIGURATIONGateway();
                        HttpContext.Current.Items.Add("SISMONRules.TASK_CONFIGURATIONGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "TASK_CONFIGURATION"; }
        }

        protected override string RuleName
        {
            get {return typeof(TASK_CONFIGURATIONGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, TASK_CONFIGURATIONObject entity)
        {
            
            IMappeableTASK_CONFIGURATIONObject TASK_CONFIGURATION = (IMappeableTASK_CONFIGURATIONObject)entity;
            TASK_CONFIGURATION.HydrateFields(
            reader.GetInt32(0),
reader.GetInt32(1),
reader.GetString(2),
reader.GetBoolean(3),
reader.GetByte(4));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(TASK_CONFIGURATIONObject entity)
        {

            IMappeableTASK_CONFIGURATIONObject TASK_CONFIGURATION = (IMappeableTASK_CONFIGURATIONObject)entity;
            return TASK_CONFIGURATION.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(TASK_CONFIGURATIONObject entity)
        {

            IMappeableTASK_CONFIGURATIONObject TASK_CONFIGURATION = (IMappeableTASK_CONFIGURATIONObject)entity;
            return TASK_CONFIGURATION.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(TASK_CONFIGURATIONObject entity)
        {

            IMappeableTASK_CONFIGURATIONObject TASK_CONFIGURATION = (IMappeableTASK_CONFIGURATIONObject)entity;
            return TASK_CONFIGURATION.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(TASK_CONFIGURATIONObject row, object[] parameters)
        {
            ((IMappeableTASK_CONFIGURATIONObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "sm_";
        }


        /// <summary>
        /// Get a TASK_CONFIGURATIONObject by execute a SQL Query Text
        /// </summary>
        public TASK_CONFIGURATIONObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a TASK_CONFIGURATIONObjectList by execute a SQL Query Text
        /// </summary>
        public TASK_CONFIGURATIONObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a TASK_CONFIGURATIONObject by calling a Stored Procedure
        /// </summary>
        public TASK_CONFIGURATIONObject GetOne(System.Int32 Id_Task_Configuration)
        {
            return base.GetOne(new TASK_CONFIGURATIONObject(Id_Task_Configuration));
        }


        // GetBy Objects and Params
            


        

        /// <summary>
        /// Get a TASK_CONFIGURATIONObjectList by calling a Stored Procedure
        /// </summary>
        public TASK_CONFIGURATIONObjectList GetByTASK(DbTransaction transaction,System.Int32 Id_Task)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "TASK_CONFIGURATION_GetByTASK", Id_Task);
        }

        /// <summary>
        /// Get a TASK_CONFIGURATIONObjectList by calling a Stored Procedure
        /// </summary>
        public TASK_CONFIGURATIONObjectList GetByTASK(DbTransaction transaction, IUniqueIdentifiable TASK)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "TASK_CONFIGURATION_GetByTASK", TASK.Identifier());
        }

    

        

        /// <summary>
        /// Get a TASK_CONFIGURATIONObjectList by calling a Stored Procedure
        /// </summary>
        public TASK_CONFIGURATIONObjectList GetByTASK(System.Int32 Id_Task)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "TASK_CONFIGURATION_GetByTASK", Id_Task);
        }

        /// <summary>
        /// Get a TASK_CONFIGURATIONObjectList by calling a Stored Procedure
        /// </summary>
        public TASK_CONFIGURATIONObjectList GetByTASK(IUniqueIdentifiable TASK)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "TASK_CONFIGURATION_GetByTASK", TASK.Identifier());
        }

    

        /// <summary>
        /// Delete TASK_CONFIGURATION
        /// </summary>
        public void Delete(System.Int32 Id_Task_Configuration)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "TASK_CONFIGURATION_Delete", Id_Task_Configuration);
        }

        /// <summary>
        /// Delete TASK_CONFIGURATION
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 Id_Task_Configuration)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "TASK_CONFIGURATION_Delete", Id_Task_Configuration);
        }

            

        

        /// <summary>
        /// Delete TASK_CONFIGURATION by TASK
        /// </summary>
        public void DeleteByTASK(System.Int32 Id_Task)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "TASK_CONFIGURATION_DeleteByTASK", Id_Task);
        }

        /// <summary>
        /// Delete TASK_CONFIGURATION by TASK
        /// </summary>
        public void DeleteByTASK(DbTransaction transaction, System.Int32 Id_Task)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "TASK_CONFIGURATION_DeleteByTASK", Id_Task);
        }

        /// <summary>
        /// Delete TASK_CONFIGURATION by TASK
        /// </summary>
        public void DeleteByTASK(IUniqueIdentifiable TASK)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "TASK_CONFIGURATION_DeleteByTASK", TASK.Identifier());
        }

        /// <summary>
        /// Delete TASK_CONFIGURATION by TASK
        /// </summary>
        public void DeleteByTASK(DbTransaction transaction, IUniqueIdentifiable TASK)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "TASK_CONFIGURATION_DeleteByTASK", TASK.Identifier());
        }


    


        //Database Queries 
        
            

        /// <summary>
        /// 
        /// </summary>
        public System.Int32 DeleteByTask(System.Int32 Id_Task) {
            
            return (System.Int32) base.DataBaseHelper.ExecuteScalarByStoredProcedure(StoredProceduresPrefix() + "TASK_CONFIGURATION_DeleteByTask" , Id_Task);
            
        }

        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 DeleteByTask(DbTransaction transaction , System.Int32 Id_Task) {
            
            return (System.Int32) base.DataBaseHelper.ExecuteScalarByStoredProcedure(transaction, StoredProceduresPrefix() + "TASK_CONFIGURATION_DeleteByTask" , Id_Task);
            
        }


        
            

        /// <summary>
        /// 
        /// </summary>
        public System.Int32 ChangeStatus(System.Int32 Id_Task, System.Byte ID_STATUS) {
            
            return (System.Int32) base.DataBaseHelper.ExecuteScalarByStoredProcedure(StoredProceduresPrefix() + "TASK_CONFIGURATION_ChangeStatus" , Id_Task, ID_STATUS);
            
        }

        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 ChangeStatus(DbTransaction transaction , System.Int32 Id_Task, System.Byte ID_STATUS) {
            
            return (System.Int32) base.DataBaseHelper.ExecuteScalarByStoredProcedure(transaction, StoredProceduresPrefix() + "TASK_CONFIGURATION_ChangeStatus" , Id_Task, ID_STATUS);
            
        }


        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








