
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is ALERT_TYPEObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace SISMONRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ALERT_TYPEObject : BaseObject, IMappeableALERT_TYPEObject, IUniqueIdentifiable, IEquatable<ALERT_TYPEObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public ALERT_TYPEObject(): base()
        {

			_Id_Alert_Type =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public ALERT_TYPEObject(
			System.Int32 Id_Alert_Type): base()
        {

			_Id_Alert_Type = Id_Alert_Type;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public ALERT_TYPEObject(
			System.Int32 Id_Alert_Type,
			System.String Description): base()
        {

			_Id_Alert_Type = Id_Alert_Type;
			_Description = Description;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _Id_Alert_Type;
/// <summary>
/// 
/// </summary>
protected System.String _Description;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 Id_Alert_Type
        {
            get
            {
                return _Id_Alert_Type;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Description
        {
            get
            {
                return _Description;
            }
            
            set
            {
                base.PropertyModified();
                _Description = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            ALERT_TYPEObject newObject;
            ALERT_TYPEObject newOriginalValue;

            newObject = (ALERT_TYPEObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (ALERT_TYPEObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new ALERT_TYPEObject OriginalValue()
        {
            return (ALERT_TYPEObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableALERT_TYPEObject.HydrateFields(
			System.Int32 Id_Alert_Type,
			System.String Description)
        {
        _Id_Alert_Type = Id_Alert_Type;
_Description = Description;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableALERT_TYPEObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[2];
            _myArray[0] = _Id_Alert_Type;
_myArray[1] = _Description;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableALERT_TYPEObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[2];
            _myArray[0] = _Id_Alert_Type;
_myArray[1] = _Description;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableALERT_TYPEObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _Id_Alert_Type;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableALERT_TYPEObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _Id_Alert_Type = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            ALERT_TYPEObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.Id_Alert_Type};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(ALERT_TYPEObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableALERT_TYPEObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 Id_Alert_Type, 
			System.String Description);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class ALERT_TYPEObjectList : ObjectList<ALERT_TYPEObject>
    {
    }
}

namespace SISMONRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ALERT_TYPEObjectListView
        : ObjectListView<Objects.ALERT_TYPEObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public ALERT_TYPEObjectListView(Objects.ALERT_TYPEObjectList list): base(list)
        {
        }
    }
}


