
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 
// This is a partial class file. The other one is COST_REPLACEMENTObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace SISMONRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class COST_REPLACEMENTObject : BaseObject, IMappeableCOST_REPLACEMENTObject, IUniqueIdentifiable, IEquatable<COST_REPLACEMENTObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public COST_REPLACEMENTObject(): base()
        {


        }

        /// <summary>
        /// 
        /// </summary>
        public COST_REPLACEMENTObject(
			System.String Keyword): base()
        {

			_Keyword = Keyword;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public COST_REPLACEMENTObject(
			System.String Keyword,
			System.Decimal Cost,
			System.Byte Id_Status,
			System.String STATUSString): base()
        {

			_Keyword = Keyword;
			_Cost = Cost;
			_Id_Status = Id_Status;
			_STATUSString = STATUSString;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        /// <summary>
        /// 
        /// </summary>
        public event EventHandler<DescriptionFieldEventArg> Update_STATUSString;
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.String _Keyword;
/// <summary>
/// 
/// </summary>
protected System.Decimal _Cost;
/// <summary>
/// 
/// </summary>
protected System.Byte _Id_Status;
/// <summary>
/// 
/// </summary>
protected System.String _STATUSString;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Keyword
        {
            get
            {
                return _Keyword;
            }
            
            set
            {
                base.PropertyModified();
                _Keyword = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Decimal Cost
        {
            get
            {
                return _Cost;
            }
            
            set
            {
                base.PropertyModified();
                _Cost = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Byte Id_Status
        {
            get
            {
                return _Id_Status;
            }
            
            set
            {
                base.PropertyModified();
                _Id_Status = value;
                                
                if (Update_STATUSString != null)
                {
                    DescriptionFieldEventArg e = new DescriptionFieldEventArg(new STATUSObject (_Id_Status));
                    Update_STATUSString(this, e);
                    _STATUSString = e.DescriptionString;
                }                
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String STATUSString
        {
            get
            {
                return _STATUSString;
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            COST_REPLACEMENTObject newObject;
            COST_REPLACEMENTObject newOriginalValue;

            newObject = (COST_REPLACEMENTObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (COST_REPLACEMENTObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new COST_REPLACEMENTObject OriginalValue()
        {
            return (COST_REPLACEMENTObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableCOST_REPLACEMENTObject.HydrateFields(
			System.String Keyword,
			System.Decimal Cost,
			System.Byte Id_Status,
			System.String STATUSString)
        {
        _Keyword = Keyword;
_Cost = Cost;
_Id_Status = Id_Status;
_STATUSString = STATUSString;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableCOST_REPLACEMENTObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[3];
            _myArray[0] = _Keyword;
_myArray[1] = _Cost;
_myArray[2] = _Id_Status;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableCOST_REPLACEMENTObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[4];
            _myArray[0] = _Keyword;
_myArray[1] = _Cost;
_myArray[2] = _Id_Status;
_myArray[3] = this.OriginalValue()._Keyword;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableCOST_REPLACEMENTObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _Keyword;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableCOST_REPLACEMENTObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            
        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            COST_REPLACEMENTObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.Keyword};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(COST_REPLACEMENTObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableCOST_REPLACEMENTObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.String Keyword, 
			System.Decimal Cost, 
			System.Byte Id_Status, 
			System.String STATUSString);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class COST_REPLACEMENTObjectList : ObjectList<COST_REPLACEMENTObject>
    {
    }
}

namespace SISMONRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class COST_REPLACEMENTObjectListView
        : ObjectListView<Objects.COST_REPLACEMENTObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public COST_REPLACEMENTObjectListView(Objects.COST_REPLACEMENTObjectList list): base(list)
        {
        }
    }
}


