
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 22/10/2014 - 7:48
// This is a partial class file. The other one is TASK_ATTACHMENTObject.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using System;
using Cooperator.Framework.Core;
using Cooperator.Framework.Core.Exceptions;

namespace SISMONRules.Objects
{
    /// <summary>
    /// This class represents a Object of TASK_ATTACHMENT table.
    /// </summary>
    [Serializable]
    public partial class TASK_ATTACHMENTObject
        // : IValidable
    {

        /// <summary>
        /// Called from class constructor.
        /// </summary>
        protected override void Initialize()
        {
        }

        // /// <summary>
        // /// Called after parameterized constructor. 
        // /// </summary>
        // protected override void Initialized()
        // {       
        // //Warnging: This method is only called by parameterized contructors.
        // }

        // /// <summary>
        // /// When IValidable is implemented, this method is invoked by Gateway before Insert or Update to validate Object.
        // /// </summary>
        // public void Validate()
        // {
        //     //Example:
        //     if (string.IsNullOrEmpty(this.Name)) throw new RuleValidationException("Name can't be null");
        // }
    }

    /// <summary>
    /// This class represents a record set of TASK_ATTACHMENT table.
    /// </summary>
    public partial class TASK_ATTACHMENTObjectList
    {
         // /// <summary>
         // /// Returns a typed Dataset based on its content.
         // /// </summary>
         // public override System.Data.DataSet ToDataSet()
         // {
         //    YOUR_TYPED_DATASET MyDataSet = new YOUR_TYPED_DATASET();
         //    ObjectListHelper<TASK_ATTACHMENTObject, TASK_ATTACHMENTObjectList> Exporter = new ObjectListHelper<TASK_ATTACHMENTObject, TASK_ATTACHMENTObjectList>();
         //    Exporter.FillDataSet(MyDataSet, this);
         //    return MyDataSet;
         // }
    }
}

namespace SISMONRules.Views
{
    /// <summary>
    /// This class represents a view of an collection of TASK_ATTACHMENTObjects.
    /// </summary>
    public partial class TASK_ATTACHMENTObjectListView
    {
    }
}


