
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 12/09/2014 - 06:04 p.m.
// This is a partial class file. The other one is PROJECTMapper.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using SISMONRules.Objects;
using SISMONRules.Entities;
using Cooperator.Framework.Core;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using System.Data.Common;
using System.Reflection;
using System;

namespace SISMONRules.Mappers
{

    /// <summary>
    /// Mapper for PROJECT entity
    /// This class provide persistence methods for this entity
    /// </summary>
    public  partial class PROJECTMapper
    {
        // /// <summary>
        // /// Enables GetObjectBySQLText and GetObjectListBySQLText methods.
        // /// </summary>
        //protected override bool SQLQueriesEnabled()
        //{
        //    return true;
        //}

        // /// <summary>
        // /// Checks for security ritghs
        // /// </summary>
        //protected override bool CheckForSecurityRights(SecurityRights action, PROJECTList ObjectListOrEntityList)
        //{
        //    switch (action)
        //    {
        //        case SecurityRights.Read:
        //            return true;
        //        case SecurityRights.Insert:
        //            return true;
        //        case SecurityRights.Update:
        //            return true;
        //        case SecurityRights.Delete:
        //            return true;
        //    }
        //    return false;
        //}

    }

}


namespace SISMONRules.Loaders
{

    /// <summary>
    /// Loader for PROJECT entity
    /// This class provide get methods for this entity
    /// </summary>
    public partial class PROJECTLoader
    {
    }

}



